name:                icomp
version:             0.1.0.0
github:              "alter2000/icomp"
license:             BSD3
author:              "Jor Bashllari"
maintainer:          "altnate2000@gmail.com"
copyright:           "me"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alter2000/icomp#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  icomp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icomp

tests:
  icomp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icomp
